apply plugin: 'com.android.application'

android {
    namespace 'com.example.pdfsignatureverifier'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.pdfsignatureverifier"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'com.tom_roush:pdfbox-android:2.0.27.0'
}
